%YAML:1.0

# Modify test.InitVIOTmpPath and bagfile to the correct path
# Path to save tmp files/results
test.InitVIOTmpPath: "/home/nvidia/catkin_ws/src/orb_slam_2_ros/vi_results"

## For good initialization (no movement at the beginning for some bag)
test.DiscardTime: 0
# bagfile: "/home/hri/Documents/SLAM_Dataset/EuRoC/rosbag_file/MH_01_easy.bag"
## bad: V1_03_difficult(wrong), V2_03_difficult(lost)
## not so good(cant close loop without loopclosure): V1_02_medium, V2_02_medium, MH_05_difficult
## good: V1_01_easy, V2_01_easy, MH_01_easy, MH_02_easy, MH_03_medium, MH_04_difficult

# test.DiscardTime: 18
#bagfile: "/home/hri/Documents/SLAM_Dataset/EuRoC/rosbag_file/MH_03_medium.bag"

#bagfile: "/home/hri/Documents/SLAM_Dataset/EuRoC/rosbag_file/MH_04_difficult.bag"
#bagfile: "/home/hri/Documents/SLAM_Dataset/EuRoC/rosbag_file/MH_05_difficult.bag"
#bagfile: "/home/hri/Documents/SLAM_Dataset/EuRoC/rosbag_file/MH_02_easy.bag"
#bagfile: "/home/hri/Documents/SLAM_Dataset/EuRoC/rosbag_file/MH_01_easy.bag"
#bagfile: "/home/hri/Documents/SLAM_Dataset/EuRoC/rosbag_file/V2_02_medium.bag"
#bagfile: "/home/hri/Documents/SLAM_Dataset/EuRoC/rosbag_file/V2_01_easy.bag"
#bagfile: "/home/hri/Documents/SLAM_Dataset/EuRoC/rosbag_file/V1_02_medium.bag"
#bagfile: "/home/hri/Documents/SLAM_Dataset/EuRoC/rosbag_file/V1_01_easy.bag"

#bagfile: "/home/hri/Documents/SLAM_Dataset/EuRoC/rosbag_file/V1_03_difficult.bag"
#bagfile: "/home/hri/Documents/SLAM_Dataset/EuRoC/rosbag_file/V2_03_difficult.bag"


#######################################

# set running mode
# 0: Monocular; 1: MonoVI;
runningMode: 1

# set whether deactive Loop Closure detection
# 1: Deactive; 0: active
deactiveLoopClosure: 1

# set whether track LocalMap only with vision
# 1: only with vision without IMU; 0: else
onlyTrackLocalMap: 1

# set whether display the time-consuming of different section.
# 1: Display; 0: Not display
dispalyTimeStatistic: 0

# Set whether the TrackWithMotionModel() and TrackLocalMap() aid the tracking process
# when the TrackWithIMU() and TrackLocalMapWithIMU() fail
# 1: aid; 0: not aid
visionAidWhenTrackWithIMUFail: 0

# Wait local mapping end.
# Do not process next frame until local mapping is idle. (This can noly be used in read rosbag)
# Due to this waitting, the system is slow.
waitUntilLocalMapIdle: 0

# estimate Extrinsic between camera and IMU
# 1: estimate; 0: not estimate (use pre-calibration parameters)
estimateExtrinsicBetweenCameraAndIMU: 1

# create random matrix (Rbcstar_last) for the first VIO initialization
# 1: create random matrix; 0: use Identity matrix
CreateRandomMatrixLastForFirstVIOInit: 1

imutopic: "/imu/data"
imagetopic: "/camera/color/image_raw"

# Timestamp shift. Timage = Timu + image_delay
Camera.delaytoimu: 10

# acc=acc*9.8, if below is 1
IMU.multiplyG: 0

# camera-imu frame transformation, Pi = Tic * Pc
# for cam0 and imu0
Camera.Tbc:
 [ -0.0,  -1.0,   0.0, -0.035,
    1.0,   0.0,   0.0, -0.015,
   -0.0,   0.0,   1.0,  -0.02,
    0.0,   0.0,   0.0,    1.0]

# Local Window size
LocalMapping.LocalWindowSize: 10

#--------------------------------------------------------------------------------------------
# Imu Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# imu sample rate per second
IMU.rate: 150

# inertial sensor noise model parameters (static)
# gyro "white noise" [ rad / s / sqrt(Hz) ]
IMU.sigma_g: 1.6968e-04

# gyro bias diffusion [ rad / s^2 / sqrt(Hz) ]
IMU.sigma_gw: 1.9393e-05

# accel "white noise" [ m / s^2 / sqrt(Hz) ]
IMU.sigma_a: 2.0000e-3

# accel bias diffusion [ m / s^3 / sqrt(Hz) ].
IMU.sigma_aw: 3.0000e-3


